# Generated by Django 6.0.2 on 2026-02-06 05:29

import cv.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionperfil', models.CharField(max_length=50)),
                ('perfilactivo', models.BooleanField(default=True)),
                ('apellidos', models.CharField(max_length=60)),
                ('nombres', models.CharField(max_length=60)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('lugarnacimiento', models.CharField(max_length=60)),
                ('fechanacimiento', models.DateField()),
                ('numerocedula', models.CharField(max_length=10, unique=True)),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('fotoperfil', models.ImageField(blank=True, null=True, upload_to='perfil/')),
                ('estadocivil', models.CharField(max_length=50)),
                ('licenciaconducir', models.CharField(choices=[('Tipo A', 'Tipo A'), ('Tipo B', 'Tipo B'), ('Tipo C', 'Tipo C'), ('Tipo D', 'Tipo D'), ('Tipo E', 'Tipo E'), ('Tipo F', 'Tipo F'), ('Tipo G', 'Tipo G')], max_length=6)),
                ('telefonoconvencional', models.CharField(max_length=15)),
                ('telefonofijo', models.CharField(max_length=15)),
                ('direcciontrabajo', models.CharField(max_length=50)),
                ('direcciondomiciliaria', models.CharField(max_length=50)),
                ('sitioweb', models.URLField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CursoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecurso', models.CharField(max_length=100)),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
                ('totalhoras', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcioncurso', models.CharField(max_length=100)),
                ('entidadpatrocinadora', models.CharField(max_length=100)),
                ('nombrecontactoauspicia', models.CharField(max_length=100)),
                ('telefonocontactoauspicia', models.CharField(max_length=60)),
                ('emailempresapatrocinadora', models.EmailField(max_length=60)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('certificado', models.FileField(blank=True, null=True, upload_to='certificados/cursos/', validators=[cv.models.validar_extension_imagen])),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargodesempenado', models.CharField(max_length=100)),
                ('nombrempresa', models.CharField(max_length=50)),
                ('lugarempresa', models.CharField(max_length=50)),
                ('emailempresa', models.EmailField(max_length=100)),
                ('sitiowebempresa', models.URLField(max_length=100)),
                ('nombrecontactoempresarial', models.CharField(max_length=100)),
                ('telefonocontactoempresarial', models.CharField(max_length=60)),
                ('fechainiciogestion', models.DateField()),
                ('fechafingestion', models.DateField()),
                ('descripcionfunciones', models.CharField(max_length=100)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('certificado', models.FileField(blank=True, null=True, upload_to='certificados/experiencia/', validators=[cv.models.validar_extension_imagen])),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrerecurso', models.CharField(max_length=100)),
                ('clasificador', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproducto', models.CharField(max_length=100)),
                ('fechaproducto', models.DateField()),
                ('descripcion', models.CharField(max_length=100)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiporeconocimiento', models.CharField(choices=[('Académico', 'Académico'), ('Público', 'Público'), ('Privado', 'Privado')], max_length=100)),
                ('fechareconocimiento', models.DateField()),
                ('descripcionreconocimiento', models.CharField(max_length=100)),
                ('entidadpatrocinadora', models.CharField(max_length=100)),
                ('nombrecontactoauspicia', models.CharField(max_length=100)),
                ('telefonocontactoauspicia', models.CharField(max_length=15)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('certificado', models.FileField(blank=True, null=True, upload_to='certificados/reconocimientos/', validators=[cv.models.validar_extension_imagen])),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='VentaGarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproducto', models.CharField(max_length=100)),
                ('estadoproducto', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=40)),
                ('descripcion', models.CharField(max_length=100)),
                ('valordelbien', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('fechapublicacion', models.DateField(default=django.utils.timezone.now)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='venta_garage/')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.datospersonales')),
            ],
        ),
    ]
